# 写于2025.3.18 自此hexo与hugo双博客实现了完全github存储和部署触发（hugo会部署到oss上）
# 触发条件为提交message里加[D]标记
name: Sync to Blog

on:
  push:
    branches:
      - main  # 触发分支（根据你的实际分支名修改）

jobs:
  sync-posts:
    runs-on: ubuntu-latest
    # 仅在 commit message 包含 [D] 时执行
    if: contains(github.event.head_commit.message, '[D]')
    steps:
      # 步骤 1：检出当前仓库（Posts）内容
      - name: Checkout Posts
        uses: actions/checkout@v4

      # 步骤 2：克隆目标仓库（Hugo-Blog和Hexo-Blog）到临时目录，这里使用了--no-checkout不检出以及设置了sparse-checkout再稀疏检出
      - name: Clone Hugo Blog
        run: |
          git clone --depth 1 --branch "main" --no-checkout https://${{ secrets.PAT }}@github.com/winotmk/Hugo-Blog.git ./hugo_blog_temp
          cd ./hugo_blog_temp
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config core.sparseCheckout true
          echo content/posts > .git/info/sparse-checkout
          git checkout main

      - name: Clone Hexo Blog
        run: |
          git clone --depth 1 --branch "main" --no-checkout https://${{ secrets.PAT }}@github.com/winotmk/Hexo-Blog.git ./hexo_blog_temp
          cd ./hexo_blog_temp
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config core.sparseCheckout true
          echo source/_posts > .git/info/sparse-checkout
          git checkout main


      # 步骤 3：将 Posts 内容复制到 Hugo-Blog 的 content/posts 目录,Hexo-Blog 的 source/_posts 目录
      - name: Copy Files
        run: |
          rsync -av --checksum --delete \
            --include='*/' \
            --include='*.md' \
            --exclude='*' \
            --prune-empty-dirs \
            "./posts/" "./hugo_blog_temp/content/posts"
          rsync -av --checksum --delete \
            --include='*/' \
            --include='*.md' \
            --exclude='*' \
            --prune-empty-dirs \
            "./posts/" "./hexo_blog_temp/source/_posts"

        # 步骤 4：提交同步后的内容到 Hugo-Blog 仓库和 Hexo-Blog 仓库
      - name: Push hugo
        working-directory: ./hugo_blog_temp
        run: |
          git add content/posts
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update posts $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')"
            git push https://${{ secrets.PAT }}@github.com/winotmk/Hugo-Blog.git main
          else
            echo "hugo文章无修改"
          fi

      - name: Push hexo
        working-directory: ./hexo_blog_temp
        run: |
          git add source/_posts
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update posts $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')"
            git push https://${{ secrets.PAT }}@github.com/winotmk/Hexo-Blog.git main
          else
            echo "hexo文章无修改"
          fi